server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-feign

#feign自带熔断器 开启即可
feign:
  hystrix:
    enabled: true
